### ISSUE TITLE
Update discussion

### ISSUE THREAD

**Issue by hadrien-toma** [nolanlawson/tessel-pouchdb-demo#1]
Hello @nolanlawson :wave:! Several years later I am trying to put PouchDB on a Tessel 2 too! Before trying the steps you described in your article, I open this issue in order to ask you if by any chance you have any key points to share since the last time the repository was updated?

About my Tessel2:
```
INFO t2-cli: 0.1.22
INFO t2-firmware: 0.2.0
INFO Node.js: 8.11.3
```

**Comment by nolanlawson** [comment]
Hi, no, I have not tested this in a long while, sorry. :) Hopefully the original instructions still work!
